#!/usr/bin/env python3
"""Convert a micro-wake-word .tflite + .json into firmware C++ sources.

Downloads are not handled here; fetch the model first, e.g.:

    curl -L -o /tmp/okay_nabu.tflite \\
        https://raw.githubusercontent.com/esphome/micro-wake-word-models/main/models/v2/okay_nabu.tflite
    curl -L -o /tmp/okay_nabu.json  \\
        https://raw.githubusercontent.com/esphome/micro-wake-word-models/main/models/v2/okay_nabu.json
    python3 scripts/convert_mww_model.py /tmp/okay_nabu.tflite --json /tmp/okay_nabu.json

This writes:

    src/mww_model_data.h    - model bytes declaration
    src/mww_model_data.cpp  - model bytes array (const, flash)
    src/mww_model_config.h  - model metadata constants used by wake_word.cpp

Then update WAKE_WORD in src/config.h to match the new phrase.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

DEFAULT_FIRMWARE_SRC = Path(__file__).resolve().parent.parent / "src"


def format_array(values: bytes, per_line: int = 16) -> str:
    rendered = [f"0x{value:02x}" for value in values]
    return "\n".join(
        "    " + ", ".join(rendered[index : index + per_line]) + ","
        for index in range(0, len(rendered), per_line)
    )


def sniff_metadata(tflite_path: Path) -> dict:
    """Extract the streaming-model contract from the flatbuffer header.

    The TFLite schema version lives in the first 4 bytes; tensor shapes are
    read best with the `tflite` package, so this is intentionally minimal.
    """
    data = tflite_path.read_bytes()
    if len(data) < 4:
        raise ValueError("not a valid tflite file")
    schema_version = int.from_bytes(data[:4], "little")
    return {"schema_version": schema_version, "bytes": len(data)}


def cpp_identifier(name: str) -> str:
    return re.sub(r"[^A-Za-z0-9_]", "_", name)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("tflite", type=Path, help="path to the .tflite model")
    parser.add_argument("--json", type=Path, default=None, help="path to the model .json metadata")
    parser.add_argument("--out", type=Path, default=DEFAULT_FIRMWARE_SRC, help="firmware src dir")
    args = parser.parse_args()

    model_bytes = args.tflite.read_bytes()
    meta = sniff_metadata(args.tflite)

    # Model metadata from the accompanying JSON (v1/v2 key differences tolerated).
    json_data = {}
    if args.json and args.json.is_file():
        json_data = json.loads(args.json.read_text(encoding="utf-8"))

    micro = json_data.get("micro", {})
    wake_word = str(json_data.get("wake_word", args.tflite.stem))
    probability_cutoff = float(micro.get("probability_cutoff", 0.5))
    sliding_window = int(micro.get("sliding_window_size", micro.get("sliding_window_average_size", 5)))
    arena = int(micro.get("tensor_arena_size", 26080))
    step_ms = int(micro.get("feature_step_size", 10))
    model_id = cpp_identifier(args.tflite.stem)

    args.out.mkdir(parents=True, exist_ok=True)

    data_h = args.out / "mww_model_data.h"
    data_cpp = args.out / "mww_model_data.cpp"
    config_h = args.out / "mww_model_config.h"

    data_h.write_text(
        "#pragma once\n"
        "#include <stddef.h>\n"
        "#include <stdint.h>\n\n"
        f"extern const unsigned char g_mww_model_data[];\n"
        f"extern const size_t g_mww_model_data_len;\n",
        encoding="utf-8",
    )
    data_cpp.write_text(
        '#include "mww_model_data.h"\n\n'
        "alignas(16) const unsigned char g_mww_model_data[] = {\n"
        + format_array(model_bytes)
        + "\n};\n"
        f"const size_t g_mww_model_data_len = sizeof(g_mww_model_data);\n",
        encoding="utf-8",
    )
    config_h.write_text(
        "#pragma once\n"
        "// Generated by scripts/convert_mww_model.py - model metadata.\n"
        f"// Model: {args.tflite.name}\n"
        f"// Wake word: {wake_word}\n"
        f"// Schema version: {meta['schema_version']}\n"
        f"// Bytes: {meta['bytes']}\n"
        "#include <stddef.h>\n\n"
        f"constexpr const char *MWW_MODEL_NAME = \"{args.tflite.stem}\";\n"
        f"constexpr const char *MWW_WAKE_WORD = \"{wake_word}\";\n"
        f"constexpr float MWW_PROBABILITY_CUTOFF = {probability_cutoff:.3f}f;\n"
        f"constexpr int MWW_SLIDING_WINDOW_SIZE = {sliding_window};\n"
        f"constexpr size_t MWW_TENSOR_ARENA_SIZE = {arena};\n"
        f"constexpr int MWW_FEATURE_STEP_MS = {step_ms};\n",
        encoding="utf-8",
    )

    print(f"model:       {args.tflite.name} ({meta['bytes']} bytes)")
    print(f"wake word:   {wake_word}")
    print(f"cutoff:      {probability_cutoff}")
    print(f"window:      {sliding_window}")
    print(f"arena:       {arena} bytes")
    print(f"step:        {step_ms} ms")
    print(f"wrote:       {data_h}, {data_cpp}, {config_h}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
