#pragma once
// Generated by scripts/convert_mww_model.py - model metadata.
// Model: okay_nabu.tflite
// Wake word: Okay Nabu
// Schema version: 28
// Bytes: 60264
#include <stddef.h>

constexpr const char *MWW_MODEL_NAME = "okay_nabu";
constexpr const char *MWW_WAKE_WORD = "Okay Nabu";
constexpr float MWW_PROBABILITY_CUTOFF = 0.970f;
constexpr int MWW_SLIDING_WINDOW_SIZE = 5;
constexpr size_t MWW_TENSOR_ARENA_SIZE = 26080;
constexpr int MWW_FEATURE_STEP_MS = 10;
