#pragma once
// Generated by scripts/convert_mww_model.py - model metadata.
// Model: hi_vesper.tflite
// Wake word: Hi Vesper
// Schema version: 28
// Bytes: 62304
#include <stddef.h>

constexpr const char *MWW_MODEL_NAME = "hi_vesper";
constexpr const char *MWW_WAKE_WORD = "Hi Vesper";
constexpr float MWW_PROBABILITY_CUTOFF = 0.400f;
constexpr int MWW_SLIDING_WINDOW_SIZE = 5;
constexpr size_t MWW_TENSOR_ARENA_SIZE = 26080;
constexpr int MWW_FEATURE_STEP_MS = 10;
